language: node_js
node_js:
 - "stable"
before_install:
 - export CHROME_BIN=chromium-browser
services:
 - xvfb
script:
 - npm install
 - npm run build
deploy:
  provider: pages # Используем возможности GithubPages
  skip_cleanup: true # Не чистим рабочую директорию
  # GITHUB_TOKEN — код, обеспечивающий интеграцию Тревиса и Гитхаба.
  # Нужно сгенерировать тут: https://github.com/settings/tokens и добавить в настройки репозитория в Тревисе
  github_token: $GITHUB_TOKEN
